# Generated by Django 4.1.1 on 2022-09-11 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="user_likes",
            field=models.ManyToManyField(
                blank=True, related_name="posts_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
