# Generated by Django 4.1.1 on 2022-09-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_comment_body_alter_comment_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
