# Generated by Django 4.1.1 on 2022-09-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0008_alter_comment_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="name",
        ),
    ]
