# Generated by Django 4.1.1 on 2022-09-16 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_alter_comment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user_likes",
            new_name="users_like",
        ),
    ]
