# Generated by Django 4.1.1 on 2022-09-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_rename_user_likes_post_users_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="posts", verbose_name="Photo recording"
            ),
        ),
    ]
