# Generated by Django 4.1.1 on 2022-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_image_profile_profile_photo_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
