# Generated by Django 4.1.1 on 2022-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_profile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="YYYY-MM-DD", null=True),
        ),
    ]
