# Generated by Django 4.1.1 on 2022-09-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_alter_profile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateTimeField(blank=True, help_text="YYYY-MM-DD", null=True),
        ),
    ]
