# Generated by Django 4.1.1 on 2022-10-05 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("D", "Dialog"), ("C", "Chat")],
                        default="D",
                        max_length=1,
                        verbose_name="Type",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Participant"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "pub_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Message date"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.chat",
                        verbose_name="Chat",
                    ),
                ),
            ],
            options={
                "ordering": ["pub_date"],
            },
        ),
    ]
