# Generated by Django 4.1.1 on 2022-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
