# Generated by Django 4.1.1 on 2022-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0002_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="url",
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
