# Generated by Django 4.1.1 on 2022-09-14 19:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0004_alter_image_image_comment"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="image",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
