# Generated by Django 4.1.1 on 2022-09-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0005_alter_image_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="image",
            managers=[],
        ),
    ]
