# Generated by Django 4.1.1 on 2022-09-16 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("images", "0007_alter_image_managers_image_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Your nickname:",
            ),
        ),
    ]
